SELECT A~AUFNR C~VORNR C~WERKS C~STEUS C~KTSCH C~LTXA1 D~ARBPL E~BMSCH
           E~VGW02 E~VGE02 E~VGW03 E~VGE03 E~VGW06 E~VGE06 E~VGW05 E~VGE05 MAX( G~ISTAT ) AS ISTAT *G~TXT04
      FROM AUFK AS A JOIN AFKO AS B ON A~AUFNR = B~AUFNR
           JOIN AFVC AS C ON C~AUFPL = B~AUFPL
           JOIN CRHD AS D ON D~OBJID = C~ARBID
           JOIN AFVV AS E ON E~AUFPL = C~AUFPL AND E~APLZL = C~APLZL
           JOIN JEST AS F ON F~OBJNR = C~OBJNR
           JOIN TJ02T AS G ON G~ISTAT = F~STAT
      INTO CORRESPONDING FIELDS OF TABLE IT_ITAB
      WHERE A~AUFNR IN AUFNR AND G~SPRAS = 'EN'
      GROUP BY A~AUFNR C~VORNR C~WERKS C~STEUS C~KTSCH C~LTXA1 D~ARBPL E~BMSCH
           E~VGW02 E~VGE02 E~VGW03 E~VGE03 E~VGW06 E~VGE06 E~VGW05 E~VGE05 G~TXT04
*      ORDER BY A~AUFNR C~VORNR G~ISTAT

*      AND A~AUART IN ( 'ZP42', 'ZRDA', 'ZRMC', 'ZS40', 'ZS41', 'ZS42', 'ZS45' )
*      AND C~STEUS IN ( 'ZPO1','ZP11', 'SM01' )
*      AND F~STAT <> 'I0013'
      .

*     Get last group member based on group size.
*      LOOP AT IT_ITAB INTO DATA(WA_ITAB) GROUP BY ( AUFNR = WA_ITAB-AUFNR VORNR = WA_ITAB-VORNR
*                                                    GROUP_SIZE = GROUP SIZE )
*                                                  WITHOUT MEMBERS INTO DATA(KEY).
*        IF SY-TABIX = 1 AND KEY-GROUP_SIZE > 1.
*          DELETE IT_ITAB FROM SY-TABIX TO KEY-GROUP_SIZE - 1.
*        ELSEIF KEY-GROUP_SIZE > 1.
*          DELETE IT_ITAB FROM SY-TABIX TO ( KEY-GROUP_SIZE + ( SY-TABIX - 2 ) ).
*        ENDIF.
*      ENDLOOP.
